name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main  # ou a branch que você usa como principal

permissions:
  contents: write    # Permite o workflow criar/atualizar branch gh-pages
  pages: write       # Permite publicar no GitHub Pages
  id-token: write    # Permissão necessária para OIDC e deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Build and deploy
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./  # Se o HTML está na raiz do repo

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
